[package]
name = "netflix_analysis"
version = "0.1.0"
authors = ["Payton Breck <pbreck@bu.edu>"]
edition = "2018"

[dependencies]
csv = "1.1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
plotters = "0.3"

[dev-dependencies]
